#!/bin/bash
python3 -m verl.trainer.main_ppo \
  data.train_files=$DATA_DIR/train.parquet \
  data.val_files=$DATA_DIR/test.parquet \
  data.train_batch_size=2 \
  data.val_batch_size=2 \
  data.max_prompt_length=32 \
  data.max_response_length=32 \
  +data.max_length=64 \
  +trainer.channel_last_memory=true \
  actor_rollout_ref.model.path=$BASE_MODEL \
  actor_rollout_ref.actor.optim.lr=1e-6 \
  actor_rollout_ref.actor.ppo_mini_batch_size=16 \
  actor_rollout_ref.actor.ppo_micro_batch_size=2 \
  actor_rollout_ref.rollout.log_prob_micro_batch_size=2 \
  actor_rollout_ref.rollout.tensor_model_parallel_size=2 \
  actor_rollout_ref.rollout.gpu_memory_utilization=0.2 \
  actor_rollout_ref.ref.log_prob_micro_batch_size=2 \
  critic.model.enable_gradient_checkpointing=True \
  critic.optim.lr=1e-5 \
  critic.model.path=$BASE_MODEL \
  critic.ppo_mini_batch_size=16 \
  critic.ppo_micro_batch_size=2 \
  algorithm.kl_ctrl.kl_coef=0.001 \
  trainer.logger=['wandb'] \
  +trainer.val_before_train=False \
  trainer.default_hdfs_dir=null \
  trainer.n_gpus_per_node=2 \
  trainer.nnodes=1 \
  +trainer.fp16=False \
  +trainer.bf16=True \
  +trainer.activation_checkpointing=True \
  +trainer.num_workers=0 \
  trainer.save_freq=100 \
  trainer.test_freq=100 \
  trainer.project_name=TinyZero \
  trainer.experiment_name=$EXPERIMENT_NAME \
  trainer.total_epochs=15 2>&1 | tee verl_demo.log \
  +trainer.enable_dynamic_batch=true \
  +trainer.min_batch_size=1 \
  +trainer.max_batch_size=4  